### PR TITLE
Feature-2

### PR DESCRIPTION
**Pull request by KristinaTalalaievska**
## Checklist
- [ ] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by datatoinsights** [comment]
Hi Kristina,  As all of us will need to have a video link added to the README file, could you please add your name next to the video link? Thanks.

**Comment by KristinaTalalaievska** [comment]
Hi Caroline, 
I've added my name next to the link. Thank you for your comment

**Comment by datatoinsights** [comment]
Approved

**Review by KristinaTalalaievska — COMMENTED** [review]
Approved

**Pull request merged**
